apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: main-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /ble-connect(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ble-messenger
            port:
              number: 80
      - path: /friends(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: friends-connect
            port:
              number: 80