name: Deploy to Oracle Cloud K8s

on:
  push:
    branches: [ staging, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Generate version
        id: version
        run: |
          VERSION=$(git describe --tags --always --dirty)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
    
      - name: Update version file
        run: |
          echo "export const VERSION = '${{ env.VERSION }}';" > js/version.js          

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Install OCI CLI
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          
      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/key.pem
          chmod 600 ~/.oci/config ~/.oci/key.pem        

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Update deployment image
        run: |
          kubectl set image deployment/ble-messenger ble-messenger=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}
          kubectl rollout status deployment/ble-messenger

      - name: Debug deployment
        if: failure()
        run: |
          echo "Checking pod status..."
          kubectl get pods -l app=ble-messenger
          echo "\nChecking pod details..."
          kubectl describe pods -l app=ble-messenger
          echo "\nChecking pod logs..."
          for pod in $(kubectl get pods -l app=ble-messenger -o name); do
            echo "\nLogs for $pod:"
            kubectl logs $pod --tail=50
          done          

  deploy-staging:
    needs: build-and-push
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Install and configure kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to staging
        run: |
          kubectl -n staging set image deployment/ble-messenger ble-messenger=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push.outputs.image_digest }}
          kubectl -n staging rollout status deployment/ble-messenger

  approve-production:
    needs: [build-and-push, deploy-staging]
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: production-approval
    steps:
      - name: Approval check
        run: echo "Approved for production deployment"

  deploy-production:
    needs: [build-and-push, approve-production]
    if: github.ref == 'refs/heads/staging' && needs.approve-production.result == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install and configure kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to production
        run: |
          kubectl set image deployment/ble-messenger ble-messenger=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-and-push.outputs.image_digest }}
          kubectl rollout status deployment/ble-messenger